### ISSUE TITLE
(feat): Markdown table processor support

### ISSUE THREAD

**Issue by weiyuan95** [BirthdayResearch/contented#153]
#### What would you like to be added:
As per title.

#### Why is this needed:
Useful feature to have since some data is better represented in a tabular form. For example, a glossary, schema, etc.

**Comment by fuxingloh** [comment]
This is already supported?

```md
| A | B | 
|---|---|
| 1 | 2 |
```

| A | B | 
|---|---|
| 1 | 2 |

**Comment by weiyuan95** [comment]
😱
