### ISSUE TITLE
Header with link in it does not render properly

### ISSUE THREAD

**Issue by cwkang1998** [BirthdayResearch/contented#308]
#### What happened:

When doing something like:

```md
## [A header that's a link](./something.md)
```

The header does not render on `contented write`.

If however you do a combination of links and text in the header like so:

```md
## Half a [header](something.md)
```

The text half render correctly, but the link will only appear on hover.

A visual example which is also reproduced below:

```md
---
title: Lorem 1
---

## This is a heading that is not a link

## [This is a heading that is a link](http://tempore-serpens.net/temperatvirentem)

## Half a link [here:](http://tempore-serpens.net/temperatvirentem)
## [Another: ](http://tempore-serpens.net/temperatvirentem), after a link

## There is headings above this title that is a link that is not shown.

[Normal link seems to work](http://tempore-serpens.net/temperatvirentem)
```

<img width="779" alt="Screenshot 2023-01-11 at 3 03 45 PM" src="https://user-images.githubusercontent.com/23054115/211740159-b6832d20-8f4c-4aab-921f-d3e7e0a67098.png">

#### What you expected to happen:

The heading to render as expected, with the link shown in header style if possible.

#### How to reproduce it (as minimally and precisely as possible):

https://github.com/cwkang1998/contented-bug-linked-heading

**Comment by weiyuan95** [comment]
Does this kind of file linking even work on the rendered contented site? Or are you just giving an example and intending to use it with web links?

**Comment by cwkang1998** [comment]
> Does this kind of file linking even work on the rendered contented site? Or are you just giving an example and intending to use it with web links?

For both cases, once you attempt to put a link into the heading, the phenomena happens.

As for the file linking, I'm not quite sure if it works as intended as a link, but of course if it does it'll be a great DX. But this issue focuses more on the rendering of links as a heading instead of linking.
